version: '3.8'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: mssql-container
        ports:
            - '1433:1433'
        environment:
            SA_PASSWORD: '123@123Abc'
            ACCEPT_EULA: 'Y'
            MSSQL_PID: 'Express'
        restart: always
        networks:
            - my-network

    app:
        build: .
        container_name: spring-boot-app
        depends_on:
            - db
        ports:
            - '8088:8080'
        restart: always

        environment:
            - SPRING_PROFILES_ACTIVE=docker
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
